# Generated by Django 6.0.6 on 2026-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
